### ISSUE TITLE
Import Type not showing

### ISSUE THREAD

**Issue by SlickTorpedo** [helospark/import-jar-as-project#3]
![image](https://user-images.githubusercontent.com/55722867/151681170-77c71c29-a0ee-4e7a-b111-564a2925ddd4.png)
I'm trying to import a plugin but that is all I see there is no "other" option

The howto says:
•Install the plugin
•File->Import->Other->Jar without source
•Select a jar/war file and click finish
•New project will be created from the jar

But i don't see Other under the import area can you please help? Thank you!

(Yes I've checked the plugin is installed)
_I am new to Java please don't hate_

**Comment by helospark** [comment]
@SlickTorpedo
Which Eclipse version are you using?
Do you see any errors related to the plugin in the error log window (you can turn it on in Window -> Show view -> Error log)?

**Comment by SlickTorpedo** [comment]
> @SlickTorpedo
> 
> Which Eclipse version are you using?
> 
> Do you see any errors related to the plugin in the error log window (you can turn it on in Window -> Show view -> Error log)?

I'm running the latest version of Eclipse I believe and I'll check the error log when I'm home.
