### ISSUE TITLE
how to rebuild your project

### ISSUE THREAD

**Issue by zhiyoutech** [helospark/import-jar-as-project#4]
Dear,
      I am trying to rebuild your project. but i am a beginner in Java project. i found that tycho and maven technology is used in your project. but i do not know how to rebuild your project under the Jdk1.8 or jdk 19. and the version of tycho is 2.5.0, which is a little old.
      Please provide a tutorial about how to rebuild your project.

**Comment by helospark** [comment]
Hello @hheehhaa !
You need Java 11 to build, then run `mvn clean install` in the root of the project.
The update-site will be generated in: `import-jar-as-project/com.helospark.ImportJarAsProject.p2/target/repository`. (This is the actual site hosted behind the plugin in Eclipse Marketplace)

If you just want to test it during development, you need to install the Eclipse PDE (Plug-in Development Environment) plugin, import this project as Maven project into your Eclipse then create a new run configuration with type `Eclipse Application` and run it. This will launch a new Eclipse instance with the import-jar-as-project plugin installed in this development Eclipse.

**Comment by zhiyoutech** [comment]
Greate Thanks!
