### ISSUE TITLE
Is there a zip file of this that we can download and install? 

### ISSUE THREAD

**Issue by bellecruz24** [helospark/import-jar-as-project#5]
Hello! 

Is there a zip file of this plugin so we can install it without using the Eclipse Marketplace due to certain restrictions? 
We are planning to install via Help >> Install New Software. 

Thanks!

**Comment by helospark** [comment]
Hi!
There is no zip file, but you can easily create one by downloading the files from the update site:
https://helospark.com/eclipse_plugin/import-jar-as-project/

Download these 4 files: content.jar, artifacts.jar, plugins/com.helospark.ImportJarAsProject.plugin_1.0.1.jar, features/com.helospark.ImportJarAsProjectFeature_1.0.1.jar (keep directory structure) into a local folder.

You should then be able to install then using Help >> Install New Software >> Add >> Local... -> select folder

You can also zip the files use Archive to load (make sure to not zip the folder, but the files in the folder, so the top level of the zip should be content.jar and features.jar not the folder)
